# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "ownership01", path = "exercises/01_ownership/ownership01.rs" },
  { name = "ownership01_sol", path = "solutions/01_ownership/ownership01.rs" },
  { name = "ownership02", path = "exercises/01_ownership/ownership02.rs" },
  { name = "ownership02_sol", path = "solutions/01_ownership/ownership02.rs" },
  { name = "ownership03", path = "exercises/01_ownership/ownership03.rs" },
  { name = "ownership03_sol", path = "solutions/01_ownership/ownership03.rs" },
  { name = "ownership04", path = "exercises/01_ownership/ownership04.rs" },
  { name = "ownership04_sol", path = "solutions/01_ownership/ownership04.rs" },
  { name = "ownership05", path = "exercises/01_ownership/ownership05.rs" },
  { name = "ownership05_sol", path = "solutions/01_ownership/ownership05.rs" },
  { name = "ownership06", path = "exercises/01_ownership/ownership06.rs" },
  { name = "ownership06_sol", path = "solutions/01_ownership/ownership06.rs" },
  { name = "ownership07", path = "exercises/01_ownership/ownership07.rs" },
  { name = "ownership07_sol", path = "solutions/01_ownership/ownership07.rs" },
  { name = "ownership08", path = "exercises/01_ownership/ownership08.rs" },
  { name = "ownership08_sol", path = "solutions/01_ownership/ownership08.rs" },
  { name = "ownership09", path = "exercises/01_ownership/ownership09.rs" },
  { name = "ownership09_sol", path = "solutions/01_ownership/ownership09.rs" },
  { name = "ownership10", path = "exercises/01_ownership/ownership10.rs" },
  { name = "ownership10_sol", path = "solutions/01_ownership/ownership10.rs" },
  { name = "ref_borrow01", path = "exercises/02_ref_borrow/ref_borrow01.rs" },
  { name = "ref_borrow01_sol", path = "solutions/02_ref_borrow/ref_borrow01.rs" },
  { name = "ref_borrow02", path = "exercises/02_ref_borrow/ref_borrow02.rs" },
  { name = "ref_borrow02_sol", path = "solutions/02_ref_borrow/ref_borrow02.rs" },
  { name = "ref_borrow03", path = "exercises/02_ref_borrow/ref_borrow03.rs" },
  { name = "ref_borrow03_sol", path = "solutions/02_ref_borrow/ref_borrow03.rs" },
  { name = "ref_borrow04", path = "exercises/02_ref_borrow/ref_borrow04.rs" },
  { name = "ref_borrow04_sol", path = "solutions/02_ref_borrow/ref_borrow04.rs" },
  { name = "ref_borrow05", path = "exercises/02_ref_borrow/ref_borrow05.rs" },
  { name = "ref_borrow05_sol", path = "solutions/02_ref_borrow/ref_borrow05.rs" },
  { name = "ref_borrow06", path = "exercises/02_ref_borrow/ref_borrow06.rs" },
  { name = "ref_borrow06_sol", path = "solutions/02_ref_borrow/ref_borrow06.rs" },
  { name = "ref_borrow07", path = "exercises/02_ref_borrow/ref_borrow07.rs" },
  { name = "ref_borrow07_sol", path = "solutions/02_ref_borrow/ref_borrow07.rs" },
  { name = "ref_borrow08", path = "exercises/02_ref_borrow/ref_borrow08.rs" },
  { name = "ref_borrow08_sol", path = "solutions/02_ref_borrow/ref_borrow08.rs" },
  { name = "ref_borrow09", path = "exercises/02_ref_borrow/ref_borrow09.rs" },
  { name = "ref_borrow09_sol", path = "solutions/02_ref_borrow/ref_borrow09.rs" },
  { name = "ref_borrow10", path = "exercises/02_ref_borrow/ref_borrow10.rs" },
  { name = "ref_borrow10_sol", path = "solutions/02_ref_borrow/ref_borrow10.rs" },
  { name = "ref_borrow11", path = "exercises/02_ref_borrow/ref_borrow11.rs" },
  { name = "ref_borrow11_sol", path = "solutions/02_ref_borrow/ref_borrow11.rs" },
  { name = "flow01", path = "exercises/03_flow/flow01.rs" },
  { name = "flow01_sol", path = "solutions/03_flow/flow01.rs" },
  { name = "flow02", path = "exercises/03_flow/flow02.rs" },
  { name = "flow02_sol", path = "solutions/03_flow/flow02.rs" },
  { name = "flow03", path = "exercises/03_flow/flow03.rs" },
  { name = "flow03_sol", path = "solutions/03_flow/flow03.rs" },
  { name = "flow04", path = "exercises/03_flow/flow04.rs" },
  { name = "flow04_sol", path = "solutions/03_flow/flow04.rs" },
  { name = "flow05", path = "exercises/03_flow/flow05.rs" },
  { name = "flow05_sol", path = "solutions/03_flow/flow05.rs" },
  { name = "flow06", path = "exercises/03_flow/flow06.rs" },
  { name = "flow06_sol", path = "solutions/03_flow/flow06.rs" },
  { name = "flow07", path = "exercises/03_flow/flow07.rs" },
  { name = "flow07_sol", path = "solutions/03_flow/flow07.rs" },
  { name = "flow08", path = "exercises/03_flow/flow08.rs" },
  { name = "flow08_sol", path = "solutions/03_flow/flow08.rs" },
  { name = "flow09", path = "exercises/03_flow/flow09.rs" },
  { name = "flow09_sol", path = "solutions/03_flow/flow09.rs" },
  { name = "flow10", path = "exercises/03_flow/flow10.rs" },
  { name = "flow10_sol", path = "solutions/03_flow/flow10.rs" },
  { name = "flow11", path = "exercises/03_flow/flow11.rs" },
  { name = "flow11_sol", path = "solutions/03_flow/flow11.rs" },
  { name = "match01", path = "exercises/04_match/match01.rs" },
  { name = "match01_sol", path = "solutions/04_match/match01.rs" },
  { name = "match02", path = "exercises/04_match/match02.rs" },
  { name = "match02_sol", path = "solutions/04_match/match02.rs" },
  { name = "match03", path = "exercises/04_match/match03.rs" },
  { name = "match03_sol", path = "solutions/04_match/match03.rs" },
  { name = "match04", path = "exercises/04_match/match04.rs" },
  { name = "match04_sol", path = "solutions/04_match/match04.rs" },
  { name = "match05", path = "exercises/04_match/match05.rs" },
  { name = "match05_sol", path = "solutions/04_match/match05.rs" },
  { name = "match06", path = "exercises/04_match/match06.rs" },
  { name = "match06_sol", path = "solutions/04_match/match06.rs" },
  { name = "match07", path = "exercises/04_match/match07.rs" },
  { name = "match07_sol", path = "solutions/04_match/match07.rs" },
  { name = "match08", path = "exercises/04_match/match08.rs" },
  { name = "match08_sol", path = "solutions/04_match/match08.rs" },
  { name = "match09", path = "exercises/04_match/match09.rs" },
  { name = "match09_sol", path = "solutions/04_match/match09.rs" },
]

[package]
name = "exercises"
edition = "2021"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]
